# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IOT_DT
                                 A QGIS plugin
 IOT의 센서 값을 이용하는 DT
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-12
        copyright            : (C) 2026 by lxcti
        email                : test@test.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IOT_DT class from file IOT_DT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .IOT_DT_Module import IOT_DT
    return IOT_DT(iface)
