# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IOT_DT
                                 A QGIS plugin
 IOT의 센서 값을 이용하는 DT
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-12
        git sha              : $Format:%H$
        copyright            : (C) 2026 by lxcti
        email                : test@test.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction 
from qgis.core import QgsMessageLog, Qgis
from qgis.PyQt.QtNetwork import QUdpSocket, QHostAddress

from qgis.core import QgsVectorLayer, QgsField, QgsFeature, QgsGeometry, QgsPointXY, QgsProject
from qgis.PyQt.QtCore import QVariant
from qgis.core import QgsPalLayerSettings, QgsVectorLayerSimpleLabeling, QgsTextFormat

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .IOT_DT_Module_dialog import IOT_DTDialog
import os.path
import json

class IOT_DT:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'IOT_DT_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&IOT_DT')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.socket = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('IOT_DT', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/IOT_DT_Module/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'센서값'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IOT_DT'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False

            QgsMessageLog.logMessage("First에 들어옴", "IOT_DT_Module", Qgis.Info)

            self.dlg = IOT_DTDialog()

            # UI 버튼 이벤트 연결
            self.dlg.btnStart.clicked.connect(self.on_btnStart_clicked)
            self.dlg.btnStop.clicked.connect(self.on_btnStop_clicked)
    
            # 레이어 초기화
            self.setup_temp_layer()


        # show the dialog
        self.dlg.show()
        QgsMessageLog.logMessage("dlg show함", "IOT_DT_Module", Qgis.Info)
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    # UDP로 받아온 json을 파싱해 지도를 업데이트 한다.
    def update_ui(self, message) :
        #QgsMessageLog.logMessage("update_ui", "IOT_DT_Module", Qgis.Info)
        self.dlg.mylabel.setText(message)

        # json 자료 파싱.
        try:
            data = json.loads(message)
            
            lat = data.get('lat')
            lon = data.get('lon')
            temp = data.get('Temp')
            Humidity = data.get('Humidity')

            if lat is None or lon is None or temp is None:
                QgsMessageLog.logMessage("JSON에 키가 없어서 넘어감.", "IOT_DT_Module", Qgis.Warning)
                return
            
            #QgsMessageLog.logMessage(f"lat={lat}, lon={lon}, temp={temp}", "UDP_Plugin", Qgis.Warning)
            
            # 레이어에 점(Feature) 추가
            feat = QgsFeature(self.mem_layer.fields())
            # 위경도 좌표계(EPSG:4326) 기준: x=경도(lon), y=위도(lat)
            feat.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(float(lon), float(lat))))
            feat.setAttribute("temperature", float(temp))
            feat.setAttribute("Humidity", float(Humidity))
            
            # 레이어 데이터 소스에 반영
            provider = self.mem_layer.dataProvider()
            provider.truncate() # 기존 피처 삭제
            provider.addFeatures([feat])
            
            # 실시간 반영을 위한 리페인트
            self.mem_layer.triggerRepaint()
            
        except json.JSONDecodeError:
            QgsMessageLog.logMessage(f"잘못된 JSON 형식: {message}", "UDP_Plugin", Qgis.Critical)
        except Exception as e:
            QgsMessageLog.logMessage(f"오류: {str(e)}", "UDP_Plugin", Qgis.Critical)


        

    # 이 코드는 안 쓰고 있다.
    # def on_dialog_close(self, result) :
    #     QgsMessageLog.logMessage(f"다이얼로그 닫는 중. 결과 코드: {result}", "IOT_DT_Module", Qgis.Info)
    #     self.socket.close()
    #     self.socket.readyRead.disconnect()
        


    def on_udp_data(self):
        while self.socket.hasPendingDatagrams() :
            datagram, host, port = self.socket.readDatagram(self.socket.pendingDatagramSize())

            try:
                message = datagram.decode('utf-8')
                QgsMessageLog.logMessage(f"수신된 문자열: {message}", "IOT_DT_Module", Qgis.Info)
                self.update_ui(message)

            except UnicodeDecodeError:
                QgsMessageLog.logMessage("문자열 디코딩 에러", "IOT_DT_Module", Qgis.Critical)

                '''
                Info / Warning / Critical / Success
                '''



    # 메모리 레이어 초기화
    def setup_temp_layer(self):
        # 'Point' 타입의 메모리 레이어 생성 (EPSG:4326)
        uri = "Point?crs=epsg:4326"
        self.mem_layer = QgsVectorLayer(uri, "UDP_Temperature_Points", "memory")
        
        # 필드 설정 (온도 값을 저장할 공간)
        provider = self.mem_layer.dataProvider()

        fields = [
            QgsField("temperature", QVariant.Double), 
            QgsField("Humidity", QVariant.Double)
        ]
        
        provider.addAttributes(fields)        
        self.mem_layer.updateFields()

        # 레이어를 프로젝트에 추가
        QgsProject.instance().addMapLayer(self.mem_layer)
        
        # 레이어 스타일 설정 (라벨에 온도 표시)
        self.setup_labels()

    
    # 라벨링 설정
    def setup_labels(self):
        settings = QgsPalLayerSettings()
        # settings.fieldName = "temperature" # 표시할 필드명

        expression = (
            " \"temperature\" || '°C / ' || \"humidity\" || '%' "
            )
        
        settings.fieldName = expression
        settings.isExpression = True
        
        # 텍스트 포맷 설정 (글자 크기, 색상)
        text_format = QgsTextFormat()
        text_format.setSize(14)
        settings.setFormat(text_format)
        
        # 레이어에 라벨링 적용
        self.mem_layer.setLabeling(QgsVectorLayerSimpleLabeling(settings))
        self.mem_layer.setLabelsEnabled(True)
        self.mem_layer.triggerRepaint()        


    # UI의 시작 버튼을 누른 이벤트 처리
    def on_btnStart_clicked(self) :
        QgsMessageLog.logMessage("시작 버튼 누름", "IOT_DT_Module", Qgis.Info)
        if None == self.socket :
            QgsMessageLog.logMessage("UDP 재시작", "IOT_DT_Module", Qgis.Info)
            self.socket = QUdpSocket()
            self.socket.bind(QHostAddress.LocalHost, 15551)            

        QgsMessageLog.logMessage("시작 버튼 누름2", "IOT_DT_Module", Qgis.Info)
        self.socket.readyRead.connect(self.on_udp_data)
        QgsMessageLog.logMessage("시작 버튼 누름3", "IOT_DT_Module", Qgis.Info)
    
    # UI의 멈춤 버튼을 누른 이벤트 처리
    def on_btnStop_clicked(self) :
        QgsMessageLog.logMessage("멈춤 버튼 누름", "IOT_DT_Module", Qgis.Info)
        self.socket.close()
        self.socket.readyRead.disconnect()
        self.socket = None
    
        